[project]
name = "openai-function-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "instructor>=1.4.3",
    "openai>=1.50.1",
    "requests>=2.32.3",
    "uvicorn>=0.31.0",
]
